version: "3.6"

services:

  mysql:
    image: mysql
    ports:
      - 0.0.0.0:3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: walle
      MYSQL_USER: walle
      MYSQL_PASSWORD: walle
#    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ${HOME}/.walle/mysql:/var/lib/mysql
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  web:
    build: ./
    links:
      - mysql
    expose:
      - 5000
    environment:
      - WALLE_SECRET="guess me out"
    restart: always

  gateway:
    image: nginx
    links:
      - mysql
      - web
    ports:
      - 0.0.0.0:80:80
    volumes:
      - ./fe/:/data/web/:ro
      - ./gateway/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
